# Generated by Django 5.2.7 on 2025-10-10 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('responsable', models.CharField(blank=True, max_length=200, null=True)),
                ('ville', models.CharField(max_length=200)),
                ('quartier', models.CharField(max_length=200)),
                ('nombre', models.IntegerField()),
                ('creation', models.DateField()),
                ('resume', models.TextField(blank=True, max_length=255, null=True)),
                ('infos', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='church.church')),
            ],
            options={
                'verbose_name': 'Church',
                'verbose_name_plural': 'Churches',
            },
        ),
    ]
