# Generated by Django 5.2.7 on 2025-10-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du pays')),
                ('code', models.CharField(help_text='Code ISO à 2 lettres (ex: FR, US)', max_length=2, unique=True, verbose_name='Code du pays')),
                ('phone_code', models.CharField(blank=True, help_text='Exemple: +33 pour la France', max_length=5, null=True, verbose_name='Indicatif téléphonique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['name'],
            },
        ),
    ]
