# Generated by Django 5.2.7 on 2025-11-13 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_historicalmember'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Consignes')),
                ('due_date', models.DateTimeField(verbose_name='Date de remise')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note maximale')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='Fichier joint')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='school.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Devoir',
                'verbose_name_plural': 'Devoirs',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('exam_date', models.DateTimeField(verbose_name="Date de l'examen")),
                ('duration', models.DurationField(verbose_name='Durée')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note maximale')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='school.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'étudiant")),
                ('enrollment_date', models.DateField(verbose_name="Date d'inscription")),
                ('status', models.CharField(choices=[('candidat', 'Candidat'), ('actif', 'Actif'), ('diplome', 'Diplômé'), ('abandonne', 'Abandonné'), ('suspendu', 'Suspendu')], default='candidat', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['student_number'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note obtenue')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarques')),
                ('graded_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de notation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='school.exam', verbose_name='Examen')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_exams', to='members.member', verbose_name='Noté par')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='school.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': "Résultat d'examen",
                'verbose_name_plural': "Résultats d'examens",
                'ordering': ['-graded_at'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('status', models.CharField(choices=[('inscrit', 'Inscrit'), ('en_cours', 'En cours'), ('complete', 'Complété'), ('echoue', 'Échoué'), ('abandonne', 'Abandonné')], default='inscrit', max_length=20, verbose_name='Statut')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note finale')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school.session', verbose_name='Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'session')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Fichier soumis')),
                ('comments', models.TextField(blank=True, verbose_name="Commentaires de l'étudiant")),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note obtenue')),
                ('feedback', models.TextField(blank=True, verbose_name="Feedback de l'enseignant")),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de notation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='school.assignment', verbose_name='Devoir')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to='members.member', verbose_name='Noté par')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='school.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Soumission de devoir',
                'verbose_name_plural': 'Soumissions de devoirs',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
