# Generated by Django 5.2.7 on 2025-10-10 11:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
        ('meetings', '0002_event'),
        ('members', '0002_member_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True, verbose_name='Présent(e)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='meetings.event', verbose_name='Événement')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['event__start_datetime', 'member__last_name'],
                'unique_together': {('event', 'member')},
            },
        ),
        migrations.CreateModel(
            name='Audiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre d'hommes")),
                ('women_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de femmes')),
                ('youth_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de jeunes')),
                ('children_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre d'enfants")),
                ('visitors_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de visiteurs')),
                ('day', models.DateField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church', verbose_name='Église')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='Réunion')),
            ],
            options={
                'verbose_name': 'Audience',
                'verbose_name_plural': 'Audiences',
                'ordering': ['-day'],
                'unique_together': {('meeting', 'day', 'church')},
            },
        ),
    ]
