# Generated by Django 5.2.7 on 2025-10-10 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        ('departments', '0001_initial'),
        ('members', '0002_member_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du type de collecte')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Type de collecte',
                'verbose_name_plural': 'Types de collecte',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la méthode de paiement')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Méthode de paiement',
                'verbose_name_plural': 'Méthodes de paiement',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date', models.DateField(verbose_name='Date de la collecte')),
                ('donor_guest_name', models.CharField(blank=True, max_length=200, verbose_name='Donateur (Invité)')),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Numéro de reçu')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='church.church', verbose_name='Église')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department', verbose_name='Département associé')),
                ('donor_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member', verbose_name='Donateur (Membre)')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_collections', to='members.member', verbose_name='Enregistré par')),
                ('collection_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasury.collectiontype', verbose_name='Type de collecte')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasury.paymentmethod', verbose_name='Méthode de paiement')),
            ],
            options={
                'verbose_name': 'Collecte',
                'verbose_name_plural': 'Collectes',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
