# Generated by Django 5.2.7 on 2025-10-10 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='member_photos/', verbose_name='Photo')),
                ('gender', models.CharField(choices=[('Male', 'Homme'), ('Female', 'Femme')], max_length=10, verbose_name='Sexe')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('status', models.CharField(choices=[('PASTOR', 'Pasteur'), ('ELDER', 'Ancien'), ('DEACON', 'Diacre'), ('LEADER', 'Responsable'), ('MEMBER', 'Membre'), ('ASPIRANT', 'Aspirant'), ('NOTHING', 'Nothing')], default='MEMBER', max_length=20, verbose_name='Statut')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Célibataire'), ('MARRIED', 'Marié(e)'), ('DIVORCED', 'Divorcé(e)'), ('WIDOWED', 'Veuf(ve)')], max_length=20, verbose_name='État civil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.country', verbose_name='Pays de nationalité')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
