# Generated by Django 5.2.7 on 2025-10-10 12:07

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        ('members', '0002_member_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMember',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('photo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Photo')),
                ('gender', models.CharField(choices=[('Male', 'Homme'), ('Female', 'Femme')], max_length=10, verbose_name='Sexe')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Adresse e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('status', models.CharField(choices=[('PASTOR', 'Pasteur'), ('ELDER', 'Ancien'), ('DEACON', 'Diacre'), ('LEADER', 'Responsable'), ('MEMBER', 'Membre'), ('ASPIRANT', 'Aspirant'), ('NOTHING', 'Nothing')], default='MEMBER', max_length=20, verbose_name='Statut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Membre actif')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Célibataire'), ('MARRIED', 'Marié(e)'), ('DIVORCED', 'Divorcé(e)'), ('WIDOWED', 'Veuf(ve)')], max_length=20, verbose_name='État civil')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('country', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='meetings.country', verbose_name='Pays de nationalité')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'historical Membre',
                'verbose_name_plural': 'historical Membres',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
